### ISSUE TITLE
Help to fix two 

### ISSUE THREAD

**Issue by MrWeckx** [sainadh-d/obsidian-boom#2]
I love the theme but i have two problems.
- The first one is that the title size of the pages is too big, how can i decrease the title size?

- The second point is that the elements in the file explorer are too dark when im not over them with the mouse. How can i make the a little brighter? 

Thanks man really good theme though.

**Comment by sainadhx** [comment]
Hi @MrWeckx 
* If you are talking about the Note title, the it should be done using `.view-header-title` class
Check this out in the theme
```css
.view-header-title {
    font-size: 28px;
    font-weight: 500;
}
```
* For editing elements in file explorer you need to use `.nav-file-title` class
See this for reference
```css
.nav-file-title, .nav-folder.mod-root > .nav-folder-title, .side-dock-title, .nav-folder-title, .nav-file-title-content.is-being-renamed {
	color: #5c7080;
	filter: contrast(0.9);
}
```
