### ISSUE TITLE
Source and preview panes are too wide to be read pleasantly

### ISSUE THREAD

**Issue by Eugleo** [sainadh-d/obsidian-boom#3]
Hey, according to research, the ideal line length is around 90 characters. I'd recommend adding the following to the CSS to fix the max-width for very wide screeens.

```css
.markdown-preview-section {
  max-width: 35em;
  margin-left: auto;
  margin-right: auto;
}

.markdown-source-view {
  max-width: 40em;
  margin-left: auto;
  margin-right: auto;
}
```
